name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Compile main.rs
        run: rustc main.rs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-main
          path: ./main
